### PR TITLE
Use heap types if supported

### PR DESCRIPTION
**Pull request by erlend-aasland**
- Move structure definition from header to source
- Use PyType_FromSpec to create type, if supported

Ref. https://www.python.org/dev/peps/pep-0384/#type-objects

### CODE REVIEW

**Comment by DavidLevy-Leddartech** [comment]
Sorry for the delay, all your commit looks relevant, but we have a release coming soon, that unfortunatly does not contains your commits.
We will try to include them in our development process for the next release

**Comment by erlend-aasland** [comment]
> Sorry for the delay, all your commit looks relevant, but we have a release coming soon, that unfortunatly does not contains your commits.
> We will try to include them in our development process for the next release

Great. Ping me if you have questions.

**Comment by erlend-aasland** [comment]
I'll add a PR for full GC support for the types tomorrow. When are you releasing the new version?

**Comment by DavidLevy-Leddartech** [comment]
We're giving it to Q&A later this week, probably wednesday or thursday

**Pull request merged**
